### ISSUE TITLE
Adapter verbindet sich nicht mehr und stürzt ab

### ISSUE THREAD

**Issue by Bulls91** [TA2k/ioBroker.porsche#7]
nach dem Update auf js-controller 5.0.15 stürzt der Adapter immer wieder mit der folgenden Fehlermeldung ab. Die Login-Daten haben sich nicht geändert. Kann jemand weiterhelfen?

2023-10-27 23:42:25.103 - error: porsche.0 (373928) AxiosError: Request failed with status code 403
--
2023-10-27 23:42:25.104 - error: porsche.0 (373928) {"statusCode":403,"description":"Invalid state","name":"AnomalyDetected","code":"access_denied"}
2023-10-27 23:42:25.252 - error: porsche.0 (373928) AxiosError: Request failed with status code 400
2023-10-27 23:42:25.253 - error: porsche.0 (373928) "\n \n  \n  \n  \n  \n  \n \n \n \n \n  \n \n  \n \n  \n porsche-production\n \n Oops!, something went wrong\n \n \n \n \n \n You may have pressed the back button, refreshed during login, opened too many login dialogs, or there is some issue with cookies, since we couldn't find your session. Try logging in again from the application and if the problem persists please contact the administrator.\n \n \n \n \n \n  \n  \n TECHNICAL DETAILS\n  See details for this error\n  \n  \n SUPPORT\n \n \n  Get Help\n \n \n  contact@porsche.de\n \n \n  \n \n \n \n \n  invalid_request: You may have pressed the back button, refreshed during login, opened too many login dialogs, or there is some issue with cookies, since we couldn't find your session. Try logging in again from the application and if the problem persists please contact the administrator.\n \n \n \n\n \n  \n  TRACKING ID: 85b5e4c8158466e931be\n  \n \n \n \n \n  \n \n\n"
2023-10-27 23:42:25.253 - error: porsche.0 (373928) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-10-27 23:42:25.253 - error: porsche.0 (373928) unhandled promise rejection: Cannot read properties of undefined (reading 'code')
2023-10-27 23:42:25.254 - error: porsche.0 (373928) TypeError: Cannot read properties of undefined (reading 'code')
at Porsche.login (/opt/iobroker/node_modules/iobroker.porsche/main.js:192:26)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at Porsche.onReady (/opt/iobroker/node_modules/iobroker.porsche/main.js:62:5)
2023-10-27 23:42:25.255 - error: porsche.0 (373928) Cannot read properties of undefined (reading 'code')
2023-10-27 23:42:25.261 - info: porsche.0 (373928) terminating
2023-10-27 23:42:25.261 - warn: porsche.0 (373928) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-10-27 23:42:25.763 - info: porsche.0 (373928) terminating
2023-10-27 23:42:25.796 - error: host.ioBroker Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-10-27 23:42:25.796 - error: host.ioBroker Caught by controller[0]: TypeError: Cannot read properties of undefined (reading 'code')
2023-10-27 23:42:25.796 - error: host.ioBroker Caught by controller[0]: at Porsche.login (/opt/iobroker/node_modules/iobroker.porsche/main.js:192:26)
2023-10-27 23:42:25.796 - error: host.ioBroker Caught by controller[0]: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-10-27 23:42:25.796 - error: host.ioBroker Caught by controller[0]: at Porsche.onReady (/opt/iobroker/node_modules/iobroker.porsche/main.js:62:5)
2023-10-27 23:42:25.796 - error: host.ioBroker instance system.adapter.porsche.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
20

2023-10-27 23:42:25.103 - error: porsche.0 (373928) AxiosError: Request failed with status code 403
2023-10-27 23:42:25.104 - error: porsche.0 (373928) {"statusCode":403,"description":"Invalid state","name":"AnomalyDetected","code":"access_denied"}
2023-10-27 23:42:25.252 - error: porsche.0 (373928) AxiosError: Request failed with status code 400
2023-10-27 23:42:25.253 - error: porsche.0 (373928) "\n \n \n \n \n \n \n \n \n
\n
\n \n \n \n \n \n
porsche-production

\n \n
Oops!, something went wrong

\n \n
\n
\n
\n \n You may have pressed the back button, refreshed during login, opened too many login dialogs, or there is some issue with cookies, since we couldn't find your session. Try logging in again from the application and if the problem persists please contact the administrator.\n \n

\n
\n
\n
\n \n \n
TECHNICAL DETAILS

\n [See details for this error](http://192.168.0.220:8081/%22#\%22)\n \n \n
SUPPORT

\n \n \n [Get Help](http://192.168.0.220:8081/%22https://www.porsche.com/germany/dialog/contact//%22)\n \n \n [contact@porsche.de](http://192.168.0.220:8081/%22mailto:contact@porsche.de/%22)\n \n \n \n
\n
\n
\n \n invalid_request: You may have pressed the back button, refreshed during login, opened too many login dialogs, or there is some issue with cookies, since we couldn't find your session. Try logging in again from the application and if the problem persists please contact the administrator.\n \n

\n \n\n \n \n TRACKING ID: 85b5e4c8158466e931be\n \n \n
\n
\n
\n \n \n\n"
2023-10-27 23:42:25.253 - error: porsche.0 (373928) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-10-27 23:42:25.253 - error: porsche.0 (373928) unhandled promise rejection: Cannot read properties of undefined (reading 'code')
2023-10-27 23:42:25.254 - error: porsche.0 (373928) TypeError: Cannot read properties of undefined (reading 'code')
at Porsche.login (/opt/iobroker/node_modules/iobroker.porsche/main.js:192:26)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at Porsche.onReady (/opt/iobroker/node_modules/iobroker.porsche/main.js:62:5)
2023-10-27 23:42:25.255 - error: porsche.0 (373928) Cannot read properties of undefined (reading 'code')
2023-10-27 23:42:25.261 - info: porsche.0 (373928) terminating
2023-10-27 23:42:25.261 - warn: porsche.0 (373928) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-10-27 23:42:25.763 - info: porsche.0 (373928) terminating
2023-10-27 23:42:25.796 - error: host.ioBroker Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-10-27 23:42:25.796 - error: host.ioBroker Caught by controller[0]: TypeError: Cannot read properties of undefined (reading 'code')
2023-10-27 23:42:25.796 - error: host.ioBroker Caught by controller[0]: at Porsche.login (/opt/iobroker/node_modules/iobroker.porsche/main.js:192:26)
2023-10-27 23:42:25.796 - error: host.ioBroker Caught by controller[0]: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-10-27 23:42:25.796 - error: host.ioBroker Caught by controller[0]: at Porsche.onReady (/opt/iobroker/node_modules/iobroker.porsche/main.js:62:5)
2023-10-27 23:42:25.796 - error: host.ioBroker instance system.adapter.porsche.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

**Comment by TA2k** [comment]
bitte mal 0.2.0 testen

**Comment by Bulls91** [comment]
super, funktioniert! Vielen lieben Dank :)
